import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { JSDOM } from 'jsdom';
import { setActiveConnection } from '../../dashboard-ui/app/connection/active.js';
const flush = () => new Promise(resolve => setTimeout(resolve, 0));

test('Files entry flows through the real Telegraph connector using only Bearer object routes', async t => {
  const html = await readFile(new URL('../../dashboard-ui/index.html', import.meta.url), 'utf8');
  const dom = new JSDOM(html, { url: 'https://admin.example' });
  const previous = { window: globalThis.window, document: globalThis.document, fetch: globalThis.fetch };
  Object.assign(globalThis, { window: dom.window, document: dom.window.document });
  const calls = [], saved = [], copied = [], revoked = [];
  const data = { bucket: 'media', key: 'file.txt', size: 3, content_type: 'text/plain', etag: 'listed', version: 4 };
  globalThis.fetch = async (url, options) => {
    calls.push({ url, ...options });
    if (options.method === 'HEAD') return new Response(null, { headers: { ETag: '"head-exact"', 'Content-Length': '3', 'Content-Type': 'text/plain', 'X-Telegraph-Cloud-Object-Version': '4' } });
    if (options.method === 'GET' && new URL(url).pathname.endsWith('/file.txt')) return new Response('abc', { headers: { ETag: '"head-exact"', 'Content-Type': 'text/plain' } });
    const payload = options.method === 'DELETE' ? { deleted: true } : options.method === 'PUT' ? { data } : { data: [data], has_more: false, common_prefixes: [] };
    return new Response(JSON.stringify(payload), { headers: { 'Content-Type': 'application/json' } });
  };
  dom.window.HTMLAnchorElement.prototype.click = function () { saved.push({ name: this.download, href: this.href }); };
  Object.defineProperty(dom.window.navigator, 'clipboard', { value: { async writeText(value) { copied.push(value); } } });
  t.mock.method(URL, 'createObjectURL', () => 'blob:test-download');
  t.mock.method(URL, 'revokeObjectURL', value => revoked.push(value));
  t.after(() => { setActiveConnection(null); Object.assign(globalThis, previous); dom.window.close(); });
  await import('../../dashboard-ui/app/index.js');
  const $ = id => dom.window.document.getElementById(id);
  const submit = id => $(id).dispatchEvent(new dom.window.Event('submit', { bubbles: true, cancelable: true }));
  $('connection-key').value = 'test-only-not-a-real-key'; submit('connection-form'); await flush();
  assert.equal(calls.length, 0); $('files-workspace-tab').click();
  assert.equal($('files-workspace').hidden, false); assert.equal($('data-workspace').hidden, true);
  $('bucket-input').value = 'media'; submit('open-bucket-form'); await flush();
  $('objects-table').querySelector('button').click(); await flush();
  assert.match($('object-metadata').textContent, /head-exact/);
  $('copy-object-url').click(); await flush();
  assert.equal(copied[0], 'https://telestorage.pages.dev/api/storage/media/file.txt');
  submit('download-form'); await flush();
  assert.equal(saved[0].name, 'file.txt'); assert.equal(saved[0].href, 'blob:test-download');
  const download = calls.find(call => call.method === 'GET' && call.url.endsWith('/file.txt'));
  assert.equal(download.headers.get('if-match'), '"head-exact"');
  $('delete-object').click(); $('delete-object-ack').checked = true; submit('delete-object-form'); await flush();
  assert.equal(calls.filter(call => call.method === 'DELETE').length, 1);
  const body = new Blob(['abc'], { type: 'text/plain' }); Object.defineProperty(body, 'name', { value: 'upload.txt' });
  Object.defineProperty($('upload-file'), 'files', { value: [body], configurable: true });
  $('upload-file').dispatchEvent(new dom.window.Event('change')); $('upload-ack').checked = true; submit('upload-form'); await flush();
  const upload = calls.find(call => call.method === 'PUT'); assert.equal(upload.body, body); assert.equal(upload.headers.get('content-type'), 'text/plain');
  assert.ok(calls.every(call => new URL(call.url).pathname.startsWith('/api/storage/media')));
  assert.ok(calls.every(call => call.headers.get('authorization') === 'Bearer test-only-not-a-real-key'));
  assert.ok(calls.every(call => !call.url.includes('test-only-not-a-real-key')));
  $('disconnect').click(); assert.equal($('object-url').value, ''); assert.ok(revoked.includes('blob:test-download'));
});
